import { describe, expect, it } from 'vitest';
import fixture from '@/test/fixtures/shopping-defective-v4.json';
import { type ShoppingDocumentV3, projectShoppingDocument, validateShoppingDocumentV3 } from '../shopping-document';
import { initializeShoppingDocument, readInitializedDocument } from '../shopping-initialization';
import { recoverShoppingPlacement, shoppingPlacementRecoveryCandidates } from '../shopping-placement-recovery';
import { planShoppingCommand } from '../shopping-command-planner';
import type { ShoppingCommand } from '../shopping-command';

// Generated by the actual 21c73d8 initializer during the PostgreSQL baseline
// reproduction, not by the recovery implementation. Raw originalEntry included.
const affected = () => structuredClone(fixture.originalV4) as unknown as ShoppingDocumentV3;
const legacy = () => structuredClone(fixture.legacy) as unknown as ShoppingDocumentV3;
const run = (document: ShoppingDocumentV3, mutation: ShoppingCommand['mutation'], proof = false, observedRevision = 7) =>
  planShoppingCommand({ status: 'Pending', row: { document, content_revision: 7 }, dependencyRevision: '0', pantry: [], recipes: [],
    inverse: null, inverseRevision: null, lastWriteWasInitialization: proof }, { protocol: 1, observedRevision, mutation });
const initialize = { type: 'initialize' } as const;
const resolve = (categoryKey: string) => ({ type: 'resolvePlacement', purchaseKey: 'lemon', categoryKey, anchor: null }) as const;
const category = (document: ShoppingDocumentV3) => projectShoppingDocument(document).items[0]?.categoryKey;

describe('F2 existing V4 placement recovery', () => {
  it('repairs actual defective initialization only with exact-revision provenance', () => {
    const before = affected();
    expect(category(before)).toBe('produce');
    const result = run(before, initialize, true);
    expect(result.outcome).toBe('Applied');
    expect(category(result.document)).toBe('dairy');
    expect(result.document.preferences.ingredientOrderByCategory.dairy).toEqual(['lemon']);
    expect(result.document.placementEvidence!.resolved.lemon.categories).toEqual(['produce', 'dairy']);
    expect(readInitializedDocument(result.document, validateShoppingDocumentV3)).not.toBeNull();
    expect(affected()).toEqual(before);
  });
  it('retains ambiguity and supports explicit Dairy resolution for the exact no-receipt reproduction', () => {
    const result = run(affected(), initialize);
    expect(result.outcome).toBe('Applied');
    expect(category(result.document)).toBe('legacy-placement');
    expect(result.document.placementEvidence!.unresolved.lemon).toEqual({ categories: ['produce', 'dairy'], sequences: { produce: ['lemon'] } });
    const resolved = run(result.document, resolve('dairy')).document;
    expect(category(resolved)).toBe('dairy');
    expect(run(resolved, initialize).outcome).toBe('Unchanged');
  });
  it('fresh initialization remains correct and unaffected by recovery', () => {
    const fresh = initializeShoppingDocument(legacy(), ['lemon']);
    expect(category(fresh)).toBe('dairy');
    expect(recoverShoppingPlacement(fresh, true)).toBe(fresh);
  });
  it('preserves a later explicit category move', () => {
    const moved = run(affected(), { type: 'updateCategoryPreferences', preferences: { categoryByIngredient: { lemon: 'frozen' } } }).document;
    expect(category(moved)).toBe('frozen');
    expect(recoverShoppingPlacement(moved, false)).toBe(moved);
  });
  it.each(['produce', 'dairy'])('preserves a later reorder/move to %s including hidden anchors', target => {
    const before = affected();
    before.placementEvidence!.defaults.anchor = { categoryKey: target, policyVersion: 'test' };
    (before.preferences.ingredientOrderByCategory[target] ??= []).push('anchor');
    const result = run(before, { type: 'learnOrder', draggedRowRef: 'derived:lemon', draggedOrderingKey: 'lemon', sourceCategoryKey: 'produce',
      targetRowRef: 'derived:anchor', targetOrderingKey: 'anchor', targetCategoryKey: target, placement: 'after' });
    expect(result.outcome).toBe('Applied');
    expect(result.document.preferences.ingredientOrderByCategory[target]).toEqual(['anchor', 'lemon']);
    expect(recoverShoppingPlacement(result.document, false)).toBe(result.document);
  });
  it('does not mistake a later move/reset ABA for untouched initialization', () => {
    const before = affected();
    const moved = run(before, { type: 'updateCategoryPreferences', preferences: { categoryByIngredient: { lemon: 'produce' } } }).document;
    const reset = run(moved, { type: 'updateCategoryPreferences', preferences: { categoryByIngredient: {} } }).document;
    const { organizationVersions, ...content } = reset;
    expect(content).toEqual(before); // Content is identical; Slice 9 retains the ABA history.
    expect(organizationVersions?.['purchase:lemon']).toBe(2);
    expect(run(reset, initialize).document.placementEvidence!.unresolved.lemon).toBeDefined();
  });
  it('keeps recovery harmless after repeat and a later explicit reset', () => {
    const repaired = recoverShoppingPlacement(affected(), true);
    expect(recoverShoppingPlacement(repaired, true)).toBe(repaired);
    const reset = run(repaired, { type: 'updateCategoryPreferences', preferences: { categoryByIngredient: {} } }).document;
    expect(category(reset)).toBe('produce');
    expect(recoverShoppingPlacement(reset, true)).toBe(reset);
  });
  it('keeps hidden placement and dormant slots through removal and return', () => {
    const before = affected(), entry = Object.values(before.recipeEntries)[0];
    before.itemOverrides[entry.ingredients[0].aggregateKey] = { suppressed: true };
    before.placementEvidence!.defaults.dormant = { categoryKey: 'produce', policyVersion: 'test' };
    before.preferences.ingredientOrderByCategory.produce.unshift('dormant');
    const repaired = recoverShoppingPlacement(before, true);
    expect(repaired.preferences.ingredientOrderByCategory.produce).toEqual(['dormant']);
    expect(repaired.preferences.ingredientOrderByCategory.dairy).toEqual(['lemon']);
    const removed = run(repaired, { type: 'removeRecipe', recipeId: entry.recipeId }).document;
    expect(removed.preferences).toEqual(repaired.preferences);
    removed.recipeEntries[entry.recipeId] = entry;
    expect(projectShoppingDocument(removed).excluded[0]?.categoryKey).toBe('dairy');
    expect(removed.tripVisibility?.lemon).toBe('excluded');
  });
  it('preserves unrelated content byte-for-byte', () => {
    const before = affected(), after = recoverShoppingPlacement(before, true);
    expect(after.recipeEntries).toEqual(before.recipeEntries);
    expect(after.manualItems).toEqual(before.manualItems);
    expect(after.itemOverrides).toEqual(before.itemOverrides);
    const strip = (d: ShoppingDocumentV3) => { const { categoryByIngredient: _c, ingredientOrderByCategory: _o, ...settings } = d.preferences; return settings; };
    expect(strip(after)).toEqual(strip(before));
    expect(after.placementEvidence!.defaults).toEqual(before.placementEvidence!.defaults);
  });
  it('recovers shared equivalent purchases and retained relative order once', () => {
    const before = affected(), first = Object.values(before.recipeEntries)[0];
    const twin = structuredClone(first);
    twin.recipeId = '00000000-0000-4000-8000-000000000002';
    twin.sourceEvidence!.originalEntry!.recipeId = twin.recipeId;
    before.recipeEntries[twin.recipeId] = twin;
    const lime = JSON.parse(JSON.stringify(first).replaceAll('lemon', 'lime')) as typeof first;
    lime.recipeId = '00000000-0000-4000-8000-000000000003';
    lime.sourceEvidence!.originalEntry!.recipeId = lime.recipeId;
    before.recipeEntries[lime.recipeId] = lime;
    before.placementEvidence!.defaults.lime = { ...before.placementEvidence!.defaults.lemon };
    before.preferences.ingredientOrderByCategory.produce = ['lime', 'lemon'];
    const after = recoverShoppingPlacement(before, true);
    expect(after.preferences.ingredientOrderByCategory.dairy).toEqual(['lime', 'lemon']);
    expect(projectShoppingDocument(after).items.map(row => row.categoryKey)).toEqual(['dairy', 'dairy']);
    expect(after.recipeEntries).toEqual(before.recipeEntries);
    expect(recoverShoppingPlacement(after, true)).toBe(after);
  });
  it('does not invent an interleaving with an existing destination sequence', () => {
    const before = affected();
    before.placementEvidence!.defaults.dormant = { categoryKey: 'dairy', policyVersion: 'test' };
    before.preferences.ingredientOrderByCategory.dairy = ['dormant'];
    const after = recoverShoppingPlacement(before, true);
    expect(after.preferences.ingredientOrderByCategory.dairy).toEqual(['dormant']);
    expect(after.placementEvidence!.unresolved.lemon).toBeDefined();
  });
  it.each(['partial', 'conflicting', 'occurrence'])('requires resolution for %s retained source evidence', mode => {
    const before = affected(), source = Object.values(before.recipeEntries)[0].sourceEvidence!;
    if (mode === 'partial') delete source.originalEntry;
    else if (mode === 'conflicting') (source.originalEntry!.ingredients as { defaultCategoryKey: string }[])[0].defaultCategoryKey = 'frozen';
    else (source.occurrences[0].raw as { defaultCategoryKey: string }).defaultCategoryKey = 'frozen';
    const after = recoverShoppingPlacement(before, true);
    expect(after.placementEvidence!.unresolved.lemon).toBeDefined();
    expect(after.recipeEntries).toEqual(before.recipeEntries);
  });
  it('leaves missing evidence and unaffected documents alone', () => {
    const before = affected(), entry = Object.values(before.recipeEntries)[0];
    entry.ingredients[0].defaultCategoryKey = 'produce';
    delete entry.sourceEvidence!.originalEntry;
    entry.sourceEvidence!.occurrences[0].raw = structuredClone(entry.ingredients[0]);
    expect(shoppingPlacementRecoveryCandidates(before)).toEqual({});
    expect(recoverShoppingPlacement(before, true)).toBe(before);
  });
  it('fences stale recovery and stale organization commands with the document revision', () => {
    expect(run(affected(), initialize, true, 6).outcome).toBe('Conflict');
    const repaired = recoverShoppingPlacement(affected(), true);
    expect(run(repaired, { type: 'updateCategoryPreferences', preferences: { categoryByIngredient: { lemon: 'produce' } } }, false, 6).outcome).toBe('Conflict');
  });
});
