import { test, expect } from './fixtures'
import { E2E_CONFIG } from './e2e-env'

test('inspects the compact Ingredients editor without saving', async ({ page, setupAuth }, testInfo) => {
  expect(E2E_CONFIG.target).toBe('local')
  await page.setViewportSize({ width: 1440, height: 900 })
  await setupAuth()
  await page.goto('/recipes/10000000-0000-4000-8000-000000000006?from=recipes')
  await page.getByTestId('recipe-detail-page').getByRole('button', { name: /edit recipe/i }).click()
  const dialog = page.getByRole('dialog').first()
  await dialog.getByRole('tab', { name: /^ingredients$/i }).click()
  const editor = dialog.getByTestId('ingredient-sections-editor')
  await expect(editor.getByRole('textbox', { name: 'Ingredient 1', exact: true })).toHaveValue('ground beef')

  const metrics = async () => editor.evaluate((element) => ({
    height: Math.round(element.getBoundingClientRect().height),
    viewportWidth: window.innerWidth,
    documentOverflow: document.documentElement.scrollWidth - window.innerWidth,
    rows: element.querySelectorAll('input[placeholder="Ingredient"]').length,
  }))
  const desktop = await metrics()
  expect(desktop.documentOverflow).toBeLessThanOrEqual(1)
  await dialog.evaluate((element) => {
    element.querySelectorAll('*').forEach((node) => { if (node.scrollHeight > node.clientHeight) node.scrollTop = 0 })
  })
  await page.screenshot({ path: testInfo.outputPath('ingredients-desktop-top.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  const mobile = await metrics()
  expect(mobile.documentOverflow).toBeLessThanOrEqual(1)
  await dialog.evaluate((element) => {
    element.querySelectorAll('*').forEach((node) => { if (node.scrollHeight > node.clientHeight) node.scrollTop = 0 })
  })
  await page.screenshot({ path: testInfo.outputPath('ingredients-mobile-top.png') })
  await editor.getByRole('button', { name: 'Edit prep for ingredient 1' }).click()
  await expect(editor.getByRole('textbox', { name: 'Prep for ingredient 1' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('ingredients-mobile-prep.png') })
  await editor.getByRole('textbox', { name: 'Prep for ingredient 1' }).fill('finely chopped')
  await editor.getByRole('textbox', { name: 'Prep for ingredient 1' }).press('Tab')
  await expect(editor.getByRole('button', { name: 'Edit prep for ingredient 1' })).toContainText('Prep: finely chopped')
  await page.setViewportSize({ width: 1440, height: 900 })
  await editor.getByRole('textbox', { name: 'Ingredient 1', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(editor.getByLabel('Amount for ingredient 1')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(editor.getByLabel('Unit for ingredient 1')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(editor.getByRole('textbox', { name: 'Prep for ingredient 1' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(editor.getByRole('button', { name: /Actions for ingredient 1/ })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('menuitem', { name: 'Add alternative' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menuitem', { name: 'Add alternative' })).toBeHidden()
  await expect(dialog.getByText('Discard unsaved changes?')).toHaveCount(0)

  await editor.getByRole('textbox', { name: 'Ingredient 1', exact: true }).fill('lean ground beef')
  await editor.getByLabel('Amount for ingredient 1').fill('1 1/2')
  await editor.getByLabel('Unit for ingredient 1').selectOption('lb')
  await editor.getByRole('textbox', { name: 'Prep for ingredient 1' }).fill('finely chopped')
  await editor.getByRole('button', { name: /Actions for ingredient 1/ }).click()
  await page.getByRole('menuitem', { name: 'Add alternative' }).click()
  await editor.getByLabel('Alternative 1 for ingredient 1').fill('ground turkey')
  await page.screenshot({ path: testInfo.outputPath('ingredients-desktop-alternative.png') })
  await editor.getByRole('button', { name: /Actions for ingredient 1/ }).click()
  await page.getByRole('menuitem', { name: 'Move down' }).click()
  await editor.getByRole('button', { name: /Actions for ingredient 2: lean ground beef/ }).click()
  await page.getByRole('menuitem', { name: 'Move up' }).click()
  await editor.getByRole('button', { name: /Reorder ingredient 1/ }).focus()
  await page.keyboard.press('ArrowDown')
  await editor.getByRole('button', { name: /Reorder ingredient 2/ }).focus()
  await page.keyboard.press('ArrowUp')
  await editor.getByRole('button', { name: /Remove alternative 1/ }).click()
  await editor.getByRole('button', { name: /Add ingredient$/ }).first().click()
  await expect(editor.getByRole('textbox', { name: 'Ingredient 9', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Add section' }).click()
  await editor.getByLabel('Ingredient section 2 label').fill('Cheese filling')
  await expect(editor.getByRole('button', { name: 'Delete ingredient section 1' })).toBeDisabled()
  await editor.getByRole('button', { name: /Actions for ingredient 1/ }).click()
  await page.getByRole('menuitem', { name: 'Move to section' }).hover()
  await page.getByRole('menuitem', { name: 'Cheese filling' }).click()

  await page.setViewportSize({ width: 390, height: 844 })
  await editor.getByRole('button', { name: /Actions for ingredient 1: italian sausage/ }).click()
  await expect(page.getByRole('menuitem', { name: 'Add alternative' })).toHaveCSS('opacity', '1')
  await page.waitForTimeout(200)
  await page.screenshot({ path: testInfo.outputPath('ingredients-mobile-actions.png') })
  await page.getByRole('menuitem', { name: 'Move to section' }).click()
  await expect(page.getByRole('menuitem', { name: 'Cheese filling' })).toBeVisible()
  await page.keyboard.press('Escape')
  await testInfo.attach('ingredients-density', {
    body: Buffer.from(JSON.stringify({ desktop, mobile }, null, 2)),
    contentType: 'application/json',
  })
  const fs = await import('node:fs/promises')
  await fs.writeFile(testInfo.outputPath('ingredients-density.json'), JSON.stringify({ desktop, mobile }, null, 2))
})
